Escape if data is a SchemaHash too
Otherwise only the tests pass, but combining fails because dereferencing is
errors on lib/prmd/schema.rb:90: undefined method `gsub' for nil:NilClass.